### ISSUE TITLE
Fix web page and live data records for waveform

### ISSUE THREAD

**Issue by jilavsky** [APS-USAXS/livedata#52]
9idcLAX:specFile can get too long for string in epics. We need to change to ~90 characters waveform. Unluckily, when we tried this it breaks web page and live data page. Apparently Python interprets this not as string but array of ASCII codes. 
We need to fix this so staff and users do not have to follow number of used characters too much. 
I will change the PV August 3 and this can be tested and fixed in August shot down.

**Comment by jilavsky** [comment]
@prjemian this was not addressed. Is this going to be issue for BlueSky?

**Comment by prjemian** [comment]
https://github.com/APS-USAXS/scanLog

**Comment by prjemian** [comment]
https://github.com/APS-USAXS/livedata

**Comment by prjemian** [comment]
In those two other projects, fixes were applied to get the PV value as a string waveform instead of showing it as a byte string.
