### ISSUE TITLE
waveform string displayed incorrectly

### ISSUE THREAD

**Issue by prjemian** [APS-USAXS/livedata#6]
Recent change in the [`9idcLAX:USAXS:sampleTitle`]() PV to be a longer string (using a waveform of CHAR) result in a livedata page showing the sample title as `"[0 0 0 0 ..."`

Should show as `""` instead.

**Comment by prjemian** [comment]
NOTE: For any PV that is (now) a waveform of CHAR (in the .db file, the record type is `waveform` and this field value `FTVL="CHAR"`), mark in the XML file with additional attribute: ` waveform_char="true"` (the default value is `false`).

**Comment by jilavsky** [comment]
Worked for some time, now failed again. What changed? As of 12:37 pm shows zeroes.

**Comment by prjemian** [comment]
Just set it from command line with `caput -S 9idcLAX:USAXS:sampleTitle "multi word test"` and this displayed properly for a short time (minutes), then changed to `[109 117 108 116 105  32 119 111 114 100  32 116 101 115 116   0   0   0    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0    0   0   0   0]`.

**Comment by prjemian** [comment]
Observed [live data web page](https://usaxslive.xray.aps.anl.gov/) this morning, verified *this* problem is solved.
